services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csalud_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://api.example.com"
    volumes:
      - /app/node_modules
    restart: always
